import os
import time
import argparse
import numpy as np
import torch
import requests
import uvicorn
from io import BytesIO
from PIL import Image
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import time
import brave


import sam2
from sam2.build_sam import build_sam2
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator

parser = argparse.ArgumentParser(description="Crystal Hunting Server")
parser.add_argument("--host", default="0.0.0.0", help="Server host")
parser.add_argument("--port", type=int, default=8000, help="Server port")
parser.add_argument("--sam_checkpoint", default="sam2.1_hiera_large.pt", help="Path to SAM2 checkpoint")
parser.add_argument("--model_cfg", default="configs/sam2.1/sam2.1_hiera_l.yaml", help="Model configuration file")
parser.add_argument("--output_dir", default=os.path.expanduser("~/brave"), help="Default directory for map files")
parser.add_argument("--max_area", type=int, default=700, help="Max filter area")
parser.add_argument("--min_area", type=int, default=50, help="Min filter area")
parser.add_argument("--pps", type=int, default=20, help="SAM2 mask Points per side")
parser.add_argument("--ppb", type=int, default=12, help="SAM2 mask Points per batch")

args, _ = parser.parse_known_args()

app = FastAPI(title="Crystal Hunter API")

last_mod = time.ctime(os.path.getmtime(__file__))
VERSION = f"serverbuild-{last_mod} -- brave v{brave.__version__}"

@app.get("/version")
async def get_version():
    return {"server-version": VERSION, "torch-version": torch.__version__}

class ModelManager:
    def __init__(self):
        print(f"Loading SAM2 model on startup...")
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        sam_chk = os.path.join( os.path.dirname( sam2.__file__),"../checkpoints", args.sam_checkpoint)
        self.sam2_base = build_sam2(args.model_cfg,sam_chk, device=self.device, apply_postprocessing=False)
        
        self.generator = None
        self.current_pps = None
        self.current_ppb = None

    def get_generator(self, pps, ppb):
        # Only re-instantiate if parameters pps and ppb have changed
        if self.generator is None or pps != self.current_pps or ppb != self.current_ppb:
            print(f"Updating generator: points_per_side={pps}, points_per_batch={ppb}")
            self.generator = SAM2AutomaticMaskGenerator(
                model=self.sam2_base,
                points_per_side=pps,
                points_per_batch=ppb,
                pred_iou_thresh=0.4,
                stability_score_thresh=0.7,
                stability_score_offset=0.5,
                crop_n_layers=2,
                box_nms_thresh=0.7,
                crop_n_points_downscale_factor=1,
                min_mask_region_area=2,
                use_m2m=True,
            )
            self.current_pps = pps
            self.current_ppb = ppb
        return self.generator

mm = ModelManager()
mm.get_generator(pps=args.pps, ppb=args.ppb)

# --- REQUEST SCHEMA ---
class ProcessRequest(BaseModel):
    url: str
    output_filename: str = "xmed.txt"
    max_area: int = args.max_area
    min_area: int = args.min_area
    points_per_side: int = args.pps
    points_per_batch: int = args.ppb


def get_image_from_url(url):
    try:
        response = requests.get(url, timeout=10)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        return np.array(img)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to fetch image: {e}")

@app.post("/go")
async def run_crystal_finder(req: ProcessRequest):
    start_time = time.time()
    
    image = get_image_from_url(req.url)
    
    # Get (or Re-gen) mask generator
    mask_generator = mm.get_generator(req.points_per_side, req.points_per_batch)
    
    masks_all = mask_generator.generate(image)
    
    filtered_masks = [m for m in masks_all if req.min_area < m['area'] < req.max_area]
    
    cents = []
    for m in filtered_masks:
        x, y, w, h = m['bbox']
        cents.append((x + w/2, y + h/2))
        
    # Write map file for mesh collect with BluIce
    os.makedirs(args.output_dir, exist_ok=True)
    map_path = os.path.join(args.output_dir, req.output_filename)
    
    map_content = f"# map generated by crystalFinder at {time.asctime()}\n"
    map_content += f"anchor1: 0 0\nanchor2: 0 {image.shape[0]}\n"
    map_content += f"anchor3: {image.shape[1]} {image.shape[0]}\nanchor4: {image.shape[1]} 0\n"
    
    for x, y in cents:
        map_content += f"{x:.2f} {y:.2f}\n"
        
    with open(map_path, "w") as f:
        f.write(map_content)
        
    return {
        "status": "success",
        "found": len(cents),
        "duration_sec": round(time.time() - start_time, 2),
        "params": {"pps": req.points_per_side, "ppb": req.points_per_batch},
        "saved_to": map_path
    }

if __name__ == "__main__":
    uvicorn.run(app, host=args.host, port=args.port)

